#made by vase

#selecting the shell that im using
shell /usr/bin/fish


#setting my kitty_mod key
kitty_mod alt


# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include cap-theme.conf
# END_KITTY_THEME

#Font
font_family URW Gothic
font_family      auto
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13

#transparent
background_opacity 0.80



tar_bar_style powerline
tar_powerline_style slanted

# map keys

map F1 new_window_with_cwd
map F3 next_window
map --allow-fallback=shifted,ascii kitty_mod+n new_os_window
map --allow-fallback=shifted,ascii cmd+n new_os_window
map --allow-fallback=shifted,ascii shift+cmd+d close_window
map --allow-fallback=shifted,ascii cmd+t new_tab
